-- This file should undo anything in `up.sql`

DROP TABLE IF EXISTS entry;
DROP TABLE IF EXISTS drink;
DROP TABLE IF EXISTS person;

DROP TYPE IF EXISTS VOLUME;
DROP TYPE IF EXISTS VOLUMEUNIT;
DROP TYPE IF EXISTS TIMEPERIOD;
DROP TYPE IF EXISTS REALAPPROX;