# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
import_types = ["diesel::sql_types::*", "super::{Realapprox, Timeperiod, Volumeunit, Volume}"]
patch_file = "src/schema.patch"