# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "database:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database: